inputs:
  name:
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps:
    - name: Hello There
      shell: bash
      run: |
          echo "Hello, ${{inputs.name}}"

